version: '3.8'

services:
  forum-analysis:
    build: .
    container_name: forum-analysis
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8501:8501"  # Expose Streamlit port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    command: ["streamlit", "run", "demo.py", "--server.address=0.0.0.0"] 